apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo.fullname" . }}
  labels:
    {{- include "demo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.portheader }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.portmetric }}
      targetPort: metric
      protocol: TCP
      name: metric
  selector:
    {{- include "demo.selectorLabels" . | nindent 4 }}
